
import {IoImagesOutline} from "@react-icons/all-files/io5/IoImagesOutline";
import {IoEyeOutline} from "@react-icons/all-files/io5/IoEyeOutline";
import {GiBrainstorm} from "@react-icons/all-files/gi/GiBrainstorm";
import {IoCloudDownloadOutline} from "@react-icons/all-files/io5/IoCloudDownloadOutline";

export const featuresText = [
    {
        heading: "Generate Texture Maps",
        content:
            "Generate texture maps for your 3D projects and PBR materials, using text-to-image and image-to-image AI models with Stable Diffusion. ",
        icon: GiBrainstorm,
        link: '/preview'
    },
    {
        heading: "Live Previews of Materials",
        content: `Preview the generated texture maps and PBR materials in the browser to see how they look in real-time.`,
        icon: IoEyeOutline,
        link: '/'
    },
    {
        heading: "Community Materials Gallery",
        content:
            "Browse through a gallery of materials generated by other users and download them for your projects.",
        icon: IoImagesOutline,
        link: '/gallery'
    },
    {
        heading: "Optimized Downloads",
        content: `Download the generated texture maps using filenames and folder structure optimized for your workflow.`,
        icon: IoCloudDownloadOutline,
        link: '/'
    }
];