"""empty message

Revision ID: 8dbe746d6b8b
Revises: 
Create Date: 2024-01-15 21:10:20.004818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbe746d6b8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow', sa.String(), nullable=False),
    sa.Column('maps', sa.String(), nullable=True),
    sa.Column('software', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('manifestation', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_generated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_color_prompt', sa.String(), nullable=False),
    sa.Column('base_color_url', sa.String(), nullable=False),
    sa.Column('material_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_data_id'], ['material_data.id'], name=op.f('fk_material_generated_material_data_id_material_data')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_generated')
    op.drop_table('material_data')
    # ### end Alembic commands ###
