"""empty message

Revision ID: c6a1feb4b0d2
Revises: 
Create Date: 2024-01-16 04:04:00.459910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6a1feb4b0d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow', sa.String(), nullable=False),
    sa.Column('maps', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('software', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('manifestation', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('base_color_url', sa.String(), nullable=True),
    sa.Column('normal_map_url', sa.String(), nullable=True),
    sa.Column('height_map_url', sa.String(), nullable=True),
    sa.Column('smoothness_map_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material')
    # ### end Alembic commands ###
